# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Actualizar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_actualizar(object):
    def setupUi(self, actualizar):
        actualizar.setObjectName("actualizar")
        actualizar.resize(389, 199)
        self.textEdit = QtWidgets.QTextEdit(actualizar)
        self.textEdit.setGeometry(QtCore.QRect(30, 100, 171, 91))
        self.textEdit.setObjectName("textEdit")
        self.botonActualizar = QtWidgets.QPushButton(actualizar)
        self.botonActualizar.setGeometry(QtCore.QRect(230, 100, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.botonActualizar.setFont(font)
        self.botonActualizar.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.botonActualizar.setObjectName("botonActualizar")
        self.label_2 = QtWidgets.QLabel(actualizar)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(actualizar)
        QtCore.QMetaObject.connectSlotsByName(actualizar)

    def retranslateUi(self, actualizar):
        _translate = QtCore.QCoreApplication.translate
        actualizar.setWindowTitle(_translate("actualizar", "Dialog"))
        self.botonActualizar.setText(_translate("actualizar", "ACTUALIZAR"))
        self.label_2.setText(_translate("actualizar", "<html><head/><body><p align=\"center\">SELECCIONE LA PLANTA</p><p align=\"center\">QUE DESEE ACTUALIZAR</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    actualizar = QtWidgets.QDialog()
    ui = Ui_actualizar()
    ui.setupUi(actualizar)
    actualizar.show()
    sys.exit(app.exec_())
