# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Eliminar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_eliminar(object):
    def setupUi(self, eliminar):
        eliminar.setObjectName("eliminar")
        eliminar.resize(391, 204)
        self.label_2 = QtWidgets.QLabel(eliminar)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(eliminar)
        self.textEdit.setGeometry(QtCore.QRect(40, 100, 171, 91))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(eliminar)
        self.pushButton.setGeometry(QtCore.QRect(240, 100, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(eliminar)
        QtCore.QMetaObject.connectSlotsByName(eliminar)

    def retranslateUi(self, eliminar):
        _translate = QtCore.QCoreApplication.translate
        eliminar.setWindowTitle(_translate("eliminar", "Dialog"))
        self.label_2.setText(_translate("eliminar", "<html><head/><body><p align=\"center\">SELECCIONE LA PLANTA</p><p align=\"center\">QUE DESEE ELIMINAR</p></body></html>"))
        self.pushButton.setText(_translate("eliminar", "ELIMINAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    eliminar = QtWidgets.QDialog()
    ui = Ui_eliminar()
    ui.setupUi(eliminar)
    eliminar.show()
    sys.exit(app.exec_())
