# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Actualizar import Ui_actualizar
from Eliminar import Ui_eliminar

class Ui_Dialog2(object):
    
    def openWindow6(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_actualizar()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def openWindow5(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_eliminar()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Dialog2):
        Dialog2.setObjectName("Dialog2")
        Dialog2.resize(320, 131)
        self.pushButton_5 = QtWidgets.QPushButton(Dialog2)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 20, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_5.clicked.connect(self.openWindow5)

        self.pushButton_6 = QtWidgets.QPushButton(Dialog2)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 70, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.pushButton_6.setObjectName("pushButton_6")

        self.pushButton_6.clicked.connect(self.openWindow6)

        self.retranslateUi(Dialog2)
        QtCore.QMetaObject.connectSlotsByName(Dialog2)

    def retranslateUi(self, Dialog2):
        _translate = QtCore.QCoreApplication.translate
        Dialog2.setWindowTitle(_translate("Dialog2", "Dialog"))
        self.pushButton_5.setText(_translate("Dialog2", "ELIMINAR PLANTA"))
        self.pushButton_6.setText(_translate("Dialog2", "ACTUALIZAR PLANTA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog2 = QtWidgets.QDialog()
    ui = Ui_Dialog2()
    ui.setupUi(Dialog2)
    Dialog2.show()
    sys.exit(app.exec_())
